import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

const config: Config = {
  darkMode: ['class'],
  content: ['./pages/**/*.{ts,tsx}','./components/**/*.{ts,tsx}','./app/**/*.{ts,tsx}','./src/**/*.{ts,tsx}'],
  theme: {
    container: { center: true, padding: '1rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        // FirstCry-inspired soft pastel palette
        brand: {
          blue:       '#0EA5E9',
          'blue-lt':  '#E0F2FE',
          orange:     '#F97316',
          'orange-lt':'#FFF7ED',
          pink:       '#EC4899',
          'pink-lt':  '#FDF2F8',
          purple:     '#A855F7',
          'purple-lt':'#FAF5FF',
          green:      '#22C55E',
          'green-lt': '#F0FDF4',
          yellow:     '#EAB308',
          'yellow-lt':'#FEFCE8',
          red:        '#EF4444',
          teal:       '#14B8A6',
          indigo:     '#6366F1',
        },
        primary:   { DEFAULT:'#0EA5E9', foreground:'#fff', 50:'#F0F9FF', 100:'#E0F2FE', 500:'#0EA5E9', 600:'#0284C7', 700:'#0369A1' },
        secondary: { DEFAULT:'#F97316', foreground:'#fff', 50:'#FFF7ED', 100:'#FFEDD5', 500:'#F97316', 600:'#EA580C' },
        accent:    { DEFAULT:'#EC4899', foreground:'#fff' },
        background:'#FFFFFF',
        foreground:'#111827',
        card:      { DEFAULT:'#FFFFFF', foreground:'#111827' },
        border:    '#E5E7EB',
        input:     '#F9FAFB',
        ring:      '#0EA5E9',
        muted:     { DEFAULT:'#F3F4F6', foreground:'#6B7280' },
        destructive:{ DEFAULT:'#EF4444', foreground:'#fff' },
        success:   { DEFAULT:'#22C55E', foreground:'#fff' },
        warning:   { DEFAULT:'#EAB308', foreground:'#fff' },
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['Poppins', 'Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: { lg:'0.75rem', md:'0.5rem', sm:'0.375rem', xl:'1rem', '2xl':'1.5rem', '3xl':'2rem', '4xl':'3rem' },
      boxShadow: {
        'soft':    '0 2px 20px rgba(0,0,0,0.06)',
        'card':    '0 1px 4px rgba(0,0,0,0.06), 0 4px 12px rgba(0,0,0,0.04)',
        'hover':   '0 8px 30px rgba(0,0,0,0.12)',
        'blue':    '0 4px 20px rgba(14,165,233,0.3)',
        'orange':  '0 4px 20px rgba(249,115,22,0.3)',
        'pink':    '0 4px 20px rgba(236,72,153,0.3)',
        'purple':  '0 4px 20px rgba(168,85,247,0.3)',
        'inner':   'inset 0 2px 8px rgba(0,0,0,0.06)',
      },
      animation: {
        'fade-in':      'fadeIn 0.4s ease-out',
        'slide-up':     'slideUp 0.4s ease-out',
        'slide-down':   'slideDown 0.3s ease-out',
        'scale-in':     'scaleIn 0.2s ease-out',
        'shimmer':      'shimmer 1.5s infinite linear',
        'float':        'float 3s ease-in-out infinite',
        'pulse-soft':   'pulseSoft 2s ease-in-out infinite',
        'marquee':      'marquee 30s linear infinite',
        'spin-slow':    'spin 8s linear infinite',
        'bounce-soft':  'bounceSoft 1s ease-in-out infinite',
        'accordion-down':'accordion-down 0.2s ease-out',
        'accordion-up':  'accordion-up 0.2s ease-out',
      },
      keyframes: {
        fadeIn:       { from:{opacity:'0'}, to:{opacity:'1'} },
        slideUp:      { from:{opacity:'0',transform:'translateY(20px)'}, to:{opacity:'1',transform:'translateY(0)'} },
        slideDown:    { from:{opacity:'0',transform:'translateY(-10px)'}, to:{opacity:'1',transform:'translateY(0)'} },
        scaleIn:      { from:{opacity:'0',transform:'scale(0.95)'}, to:{opacity:'1',transform:'scale(1)'} },
        shimmer:      { from:{backgroundPosition:'-200% 0'}, to:{backgroundPosition:'200% 0'} },
        float:        { '0%,100%':{transform:'translateY(0)'}, '50%':{transform:'translateY(-8px)'} },
        pulseSoft:    { '0%,100%':{opacity:'1'}, '50%':{opacity:'0.6'} },
        marquee:      { from:{transform:'translateX(0)'}, to:{transform:'translateX(-50%)'} },
        bounceSoft:   { '0%,100%':{transform:'translateY(0)'}, '50%':{transform:'translateY(-4px)'} },
        'accordion-down': { from:{height:'0'}, to:{height:'var(--radix-accordion-content-height)'} },
        'accordion-up':   { from:{height:'var(--radix-accordion-content-height)'}, to:{height:'0'} },
      },
    },
  },
  plugins: [animate],
};
export default config;
