import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      colors: {
        brand: {
          purple: '#3D35A8',
          'purple-dark': '#2C2880',
          'purple-light': '#5B52C8',
          yellow: '#FFD700',
          'yellow-dark': '#E6B800',
          'yellow-light': '#FFF0A0',
          lavender: '#EEEAFF',
          cream: '#FFFBEA',
          white: '#FFFFFF',
        },
        primary: {
          DEFAULT: '#3D35A8',
          foreground: '#FFFFFF',
          50:  '#EEEAFF',
          100: '#D5CFFF',
          200: '#B0A8FF',
          300: '#8B80FF',
          400: '#6B61EF',
          500: '#3D35A8',
          600: '#2C2880',
          700: '#201D60',
          800: '#141240',
          900: '#080720',
        },
        secondary: {
          DEFAULT: '#FFD700',
          foreground: '#1A1460',
          50:  '#FFFBEA',
          100: '#FFF3B0',
          200: '#FFE870',
          300: '#FFD700',
          400: '#E6C200',
          500: '#CCAA00',
        },
        accent: {
          DEFAULT: '#5B52C8',
          foreground: '#FFFFFF',
        },
        background: '#F8F7FF',
        foreground: '#1A1460',
        card: { DEFAULT: '#FFFFFF', foreground: '#1A1460' },
        border: '#E2DDFF',
        input: '#E2DDFF',
        ring: '#3D35A8',
        muted: { DEFAULT: '#F3F1FF', foreground: '#6B63A8' },
        destructive: { DEFAULT: '#EF4444', foreground: '#FFFFFF' },
        success: { DEFAULT: '#10B981', foreground: '#FFFFFF' },
        warning: { DEFAULT: '#FFD700', foreground: '#1A1460' },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Poppins', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        lg: '0.75rem',
        md: '0.5rem',
        sm: '0.375rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '2.5rem',
      },
      boxShadow: {
        soft:     '0 2px 15px -3px rgba(61,53,168,0.10), 0 10px 20px -2px rgba(61,53,168,0.06)',
        card:     '0 2px 8px rgba(61,53,168,0.07)',
        elevated: '0 10px 40px -10px rgba(61,53,168,0.22)',
        deep:     '0 20px 60px -15px rgba(61,53,168,0.30), 0 10px 20px -10px rgba(61,53,168,0.15)',
        glow:     '0 0 24px rgba(61,53,168,0.35)',
        'glow-lg':'0 0 40px rgba(61,53,168,0.45)',
        'yellow-glow':   '0 0 20px rgba(255,215,0,0.45)',
        'yellow-glow-lg':'0 0 40px rgba(255,215,0,0.65)',
        'inner-glow': 'inset 0 1px 0 rgba(255,255,255,0.15)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':  'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'shimmer': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.4) 50%, transparent 100%)',
      },
      animation: {
        'fade-in':        'fadeIn 0.5s ease-out',
        'slide-up':       'slideUp 0.4s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'scale-in':       'scaleIn 0.2s ease-out',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'shimmer':        'shimmer 2s infinite linear',
        'pulse-soft':     'pulseSoft 2s ease-in-out infinite',
        'marquee':        'marquee 25s linear infinite',
        'float':          'float 3s ease-in-out infinite',
        'bounce-soft':    'bounceSoft 1s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:      { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(20px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:      { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer:      { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        pulseSoft:    { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
        marquee:      { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        float:        { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        bounceSoft:   { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } },
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
    },
  },
  plugins: [animate],
};

export default config;
